# activerecord-sqlserver-adapter. SQL Server 2012 and up are supported.
# 
#
development:
  adapter: sqlserver
  host: 'localhost'
  port: 1433
  database: my_app_development
  username: 'frank_castle'
  password: 'secret'
